baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'BlowFish Extended'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]

[module.hugoVersion]
extended = true
min = "0.116.0"
